
<table class="table table-sm" id="gtReportTable">
	<thead></thead>
	<tbody>
	<tr id="gtPageSizeRow">
		<th>Page Size</th>
		<td id="gtPageSize"><?= $pageSize ?></td>
	</tr>
	<tr id="gtPageLoadRow">
		<th>Page Load Time</th>
		<td id="gtPageLoadTime"><?= $pageLoadTime ?></td>
	</tr>
	<tr id="gtPageSpeedScoreRow">
		<th>Page Speed Score</th>
		<td id="gtPageSpeedScore"><?= $pageSpeedScore ?></td>
	</tr>
	<tr>
		<th>Full Report URL</th>
        <td id="gtReportURL"><a href="<?= $reportURL ?>" target="_blank"><?= $reportURL ?></a></td>
	</tr>
	</tbody>
</table>
