<div class="container-fluid">
    <div id="info-accordion">
        <div class="card mt-0">
            <div class="card-header">
                <a class="card-link d-block" data-toggle="collapse" href="#info-gtmetrix">
                GTMetrix
                </a>
            </div>
            <div id="info-gtmetrix" class="collapse show" data-parent="#info-accordion">
            <div class="card-body">
                <h2>GTMetrix does a performance analysis of the Site URL</h2>
                <div class="alert alert-warning">
                    <h3>To run this report you will need API Credentials</h3>
                </div>
                <p>Go to <a href="https://gtmetrix.com/">https://gtmetrix.com/</a></p>
                <p>Sign in or sign up for an account.</p>
                <p>Click on &quot;User Settings&quot; on the top menu</p>
                <p>Click &quot;GTmetrix API Details&quot; under Account Settings</p>
                <p>Copy and Paste your email and API Key in the Settings tab.</p>
                <div class="alert alert-info">
                    GTMetrix free accounts allow for 20 API calls per <b>DAY</b> only. If you exceed this,  reports will fail for the remainder of the DAY.
                </div>
            </div>
            </div>
        </div>

        <div class="card mt-0">
            <div class="card-header">
                <a class="card-link d-block" data-toggle="collapse" href="#info-securitytrials">
                    Security Trails
                </a>
            </div>
            <div id="info-securitytrials" class="collapse" data-parent="#info-accordion">
                <div class="card-body">
                    <h2>Security Trails performs a Domain Lookup based on the Site URL</h2>
                    <div class="alert alert-warning">
                        <h3>Note: The report will only run on the &quot;Registerable Domain&quot;, not on subdomains. If the site is on a subdomain, the report will return results for the parent &quot;Registerable Domain&quot;</h3>
                        <h3>To run this report you will need API Credentials</h3>
                    </div>

                    <p>Go to <a href="https://securitytrails.com/">https://securitytrails.com/</a></p>
                    <p>Sign in or sign up for an account.</p>
                    <p>Click on &quot;Account&quot; on the top menu</p>
                    <p>Click &quot;Credentials&quot; on the left menu</p>
                    <p>Copy and Paste your  API Key in the Settings tab.</p>
                    <div class="alert alert-info">
                        Security Trails free accounts allow for 50 API calls per <b>MONTH</b> only. If you exceed this,  reports will fail for the remainder of the MONTH.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
