<?php
/**
 * PLUGINS
 */
$wpAllPlugins = get_plugins();
$wpActivePlugins = get_option('active_plugins');
$pluginUpdatesTransient = get_site_transient('update_plugins');
$pluginsLastChecked = $pluginUpdatesTransient->last_checked;
$pluginsCheckedArray = $pluginUpdatesTransient->checked;
$pluginsToUpdate = $pluginUpdatesTransient->response;

$activePlugins = [];
$inactivePlugins = [];

array_map(
    function ($el) use (
        $wpAllPlugins,
        $wpActivePlugins,
        $pluginsCheckedArray,
        $pluginsToUpdate,
        &$activePlugins,
        &$inactivePlugins
    ) {
        $detail = $wpAllPlugins[$el];
        if(array_key_exists($el, $pluginsToUpdate)){
            $detail['isCurrent'] = false;
            $detail['currentVersion'] = $pluginsToUpdate[$el]->new_version;
        }else{
            $detail['isCurrent'] = true;
            $detail['currentVersion'] = $detail['Version'];
        }

        if (in_array($el, $wpActivePlugins)) {
            array_push($activePlugins, $detail);
        } else {
            array_push($inactivePlugins, $detail);
        }
    },
    array_keys($wpAllPlugins)
);

?>
<table class="table table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Plugin</th>
        <th>Installed Version</th>
        <th>Current Version</th>
        <th>Up to date?</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="4"><h4>Active Plugins</h4></td>
    </tr>
    <?php foreach ($activePlugins as $active_plugin) :
        $class = $active_plugin['isCurrent'] ? 'table-success' : 'table-danger';
        ?>

        <tr class=" <?= $class ?>">
            <td><?= $active_plugin['Name'] ?></td>
            <td><?= $active_plugin['Version'] ?></td>
            <td><?= $active_plugin['currentVersion'] ?></td>
            <td><?= $active_plugin['isCurrent'] ? 'YES' : 'NO' ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="4"><h4>Not Active Plugins</h4></td>
    </tr>
    <?php foreach ($inactivePlugins as $inactive_plugin) :
        $class = $inactive_plugin['isCurrent'] ? 'table-warning' : 'table-danger';
        ?>

        <tr class=" <?= $class ?>">
            <td><?= $inactive_plugin['Name'] ?></td>
            <td><?= $inactive_plugin['Version'] ?></td>
            <td><?= $inactive_plugin['currentVersion'] ?></td>
            <td><?= $inactive_plugin['isCurrent'] ? 'YES' : 'NO' ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<p>*Notes:</p>
<ul>
    <li>All inactive plugins should be removed to improve security.</li>
    <li>All active plugins that are not up to dat should be updated.</li>
</ul>

