<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div
                    class="report-run-on-event"
                    id="saveReportsViewContainer"
                    data-action="wpe_analyser_get_saved_reports"
                    data-trigger-selector="#wpeAnalyserContainer .nav-tabs .nav-link"
                    data-trigger-event="shown.bs.tab"
                    data-body-selector="#saveReportsViewContainer .card-body"
                    data-data=""
            >

                <div class="card w-100 " id="wpe_analyser_get_saved_reports">
                    <div class="card-header">Saved Reports</div>
                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div
                    class=""
                    id="savedReportViewContainer"
                    data-action="wpe_analyser_get_saved_report"
                    data-trigger-selector=""
                    data-trigger-event=""
                    data-body-selector="#savedReportViewContainer .card-body"
                    data-data=""
            >

                <div class="card w-100 " id="wpe_analyser_get_saved_reports">
                    <div class="card-header">Report</div>
                    <div class="card-body">
                        Select Report Above
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
