<?php
$wpAllThemes = wp_get_themes();
$wpActiveTheme = wp_get_theme();

$themeUpdatesTransient = get_site_transient('update_themes');
$themesLastChecked = $themeUpdatesTransient->last_checked;
$themesCheckedArray = $themeUpdatesTransient->checked;
$themesToUpdate = $themeUpdatesTransient->response;

$inactiveThemes = [];

array_map(
    function ($el) use (
        $wpAllThemes,
        $wpActiveTheme,
        $themesCheckedArray,
        $themesToUpdate,
        &$inactiveThemes
    ) {
        if ($el === $wpActiveTheme->get_template()) return; //skip active theme
        $t = $wpAllThemes[$el];
        if (array_key_exists($el, $themesToUpdate)) {
            $inactiveThemes[$el] = [
                'theme' => $t,
                'isCurrent' => false,
                'currentVersion' => $themesToUpdate[$el]['new_version']
            ];
        } else {
            $inactiveThemes[$el] = [
                'theme' => $t,
                'isCurrent' => true,
                'currentVersion' => $t->get('Version')
            ];
        }
    },
    array_keys($wpAllThemes)
);

?>
<table class="table table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Theme</th>
        <th>Installed Version</th>
        <th>Current Version</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="4"><h4>Active Theme</h4></td>
    </tr>
    <tr class=" <?= $wpActiveTheme->update === false ? 'table-success' : 'table-danger' ?>">
        <td><?= $wpActiveTheme->display('Name') ?></td>
        <td><?= $wpActiveTheme->display('Version') ?></td>
        <td><?= $wpActiveTheme->update == false ? 'OK' : 'UPDATE NEEDED' ?></td>
    </tr>

    <tr>
        <td colspan="4"><h4>Not Active Themes</h4></td>
    </tr>

    <?php foreach ($inactiveThemes as $slug=>$theme) :

        $class = $theme['isCurrent'] ? 'table-warning' : 'table-danger';
        ?>

        <tr class=" <?= $class ?>">
            <td><?= $theme['theme']->display('Name') ?></td>
            <td><?= $theme['theme']->display('Version') ?></td>
            <td><?= $theme['currentVersion']  ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<p>*Notes:</p>
<ul>
    <li>All inactive Themes should be removed to improve security.</li>
    <li>The Active Theme should be updated.</li>
</ul>
